#!/bin/bash
# ─── Post-Generation ──────────────────────────────────────────────────────────

init_git_repo() {
    local base_dir="$1"
    local init_git
    read -r -p "  Initialize git repository? [Y/n]: " init_git
    if [[ "${init_git:-Y}" =~ ^[Yy]$ ]]; then
        (
            cd "$base_dir"
            git init -q
            git add .
            git commit -q -m "Initial project setup generated by ios-start-script"
        )
        print_success "Git repository initialized with initial commit."
    fi
}

print_summary() {
    local base_dir="$1"

    echo ""
    echo -e "${BOLD}══════════════════════════════════════════${NC}"
    print_success "Project '${PROJECT_NAME}' generated successfully!"
    echo -e "${BOLD}══════════════════════════════════════════${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. cd ${base_dir}"
    echo "  2. xcodegen generate"
    echo "  3. open ${PROJECT_NAME}.xcodeproj"
    echo ""

    if ! command -v xcodegen &> /dev/null; then
        echo -e "${YELLOW}Note: xcodegen is not installed. Install it with:${NC}"
        echo "    brew install xcodegen"
        echo ""
    fi
}
