#!/bin/bash
# ─── Post-Generation ──────────────────────────────────────────────────────────

init_git_repo() {
    local base_dir="$1"
    local init_git="${GIT_INIT}"
    local create_commit="${GIT_COMMIT}"

    # Prompt for git init if not set via args
    if [[ -z "$init_git" ]]; then
        echo -ne "  ${CYAN}◆${NC} Initialize git repository? ${DIM}[Y/n]${NC}: "
        read -r init_git
        init_git="${init_git:-Y}"
    fi

    if [[ "${init_git}" =~ ^[Yy]$ || "${init_git}" == "yes" ]]; then
        (
            cd "$base_dir"
            git init -q
        )

        # Prompt for initial commit if not set via args
        if [[ -z "$create_commit" ]]; then
            echo -ne "  ${CYAN}◆${NC} Create initial commit? ${DIM}[Y/n]${NC}: "
            read -r create_commit
            create_commit="${create_commit:-Y}"
        fi

        if [[ "${create_commit}" =~ ^[Yy]$ || "${create_commit}" == "yes" ]]; then
            (
                cd "$base_dir"
                git add .
                git commit -q -m "Initial project setup generated by ios-start-script"
            )
            print_success "Git repository initialized with initial commit."
        else
            print_success "Git repository initialized (no initial commit)."
        fi
    fi
}

print_summary() {
    local base_dir="$1"

    echo ""
    echo -e "${BOLD}══════════════════════════════════════════${NC}"
    print_success "Project '${PROJECT_NAME}' generated successfully!"
    echo -e "${BOLD}══════════════════════════════════════════${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. cd ${base_dir}"
    echo "  2. xcodegen generate"
    echo "  3. open ${PROJECT_NAME}.xcodeproj"
    echo ""

    if ! command -v xcodegen &> /dev/null; then
        echo -e "${YELLOW}Note: xcodegen is not installed. Install it with:${NC}"
        echo "    brew install xcodegen"
        echo ""
    fi
}
